/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackQuinzenalRouteImport } from './routes/feedback-quinzenal'
import { Route as FeedbackMensalRouteImport } from './routes/feedback-mensal'
import { Route as AnamneseRouteImport } from './routes/anamnese'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as FormulariosTokenRouteImport } from './routes/formularios.$token'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as AlunoTrocasRouteImport } from './routes/aluno.trocas'
import { Route as AlunoTrocarSenhaRouteImport } from './routes/aluno.trocar-senha'
import { Route as AlunoRankingRouteImport } from './routes/aluno.ranking'
import { Route as AlunoPerfilRouteImport } from './routes/aluno.perfil'
import { Route as AlunoLoginRouteImport } from './routes/aluno.login'
import { Route as AlunoEsqueciSenhaRouteImport } from './routes/aluno.esqueci-senha'
import { Route as AlunoDietaRouteImport } from './routes/aluno.dieta'
import { Route as AlunoComunidadeRouteImport } from './routes/aluno.comunidade'
import { Route as AppVisaoGeralRouteImport } from './routes/_app.visao-geral'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppFeedbacksRouteImport } from './routes/_app.feedbacks'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppCaixaSaidaRouteImport } from './routes/_app.caixa-saida'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppFormsIndexRouteImport } from './routes/_app.forms.index'
import { Route as AppFinanceiroIndexRouteImport } from './routes/_app.financeiro.index'
import { Route as AppConfiguracoesIndexRouteImport } from './routes/_app.configuracoes.index'
import { Route as AppAvaliacaoFisicaIndexRouteImport } from './routes/_app.avaliacao-fisica.index'
import { Route as AppAlunosIndexRouteImport } from './routes/_app.alunos.index'
import { Route as FormulariosIdRespostasRouteImport } from './routes/formularios.$id.respostas'
import { Route as AppFormsIdRouteImport } from './routes/_app.forms.$id'
import { Route as AppFinanceiroVendasRouteImport } from './routes/_app.financeiro.vendas'
import { Route as AppFinanceiroTransacoesRouteImport } from './routes/_app.financeiro.transacoes'
import { Route as AppFinanceiroResumoRouteImport } from './routes/_app.financeiro.resumo'
import { Route as AppFinanceiroRecebimentosRouteImport } from './routes/_app.financeiro.recebimentos'
import { Route as AppFinanceiroPlanosRouteImport } from './routes/_app.financeiro.planos'
import { Route as AppFinanceiroDespesasRouteImport } from './routes/_app.financeiro.despesas'
import { Route as AppFinanceiroContasPagarRouteImport } from './routes/_app.financeiro.contas-pagar'
import { Route as AppFinanceiroClientesRouteImport } from './routes/_app.financeiro.clientes'
import { Route as AppFinanceiroCadastrosRouteImport } from './routes/_app.financeiro.cadastros'
import { Route as AppConfiguracoesUsuariosRouteImport } from './routes/_app.configuracoes.usuarios'
import { Route as AppConfiguracoesPermissoesRouteImport } from './routes/_app.configuracoes.permissoes'
import { Route as AppConfiguracoesConexoesRouteImport } from './routes/_app.configuracoes.conexoes'
import { Route as AppConfiguracoesAutomacoesRouteImport } from './routes/_app.configuracoes.automacoes'
import { Route as AppAvaliacaoFisicaNovaRouteImport } from './routes/_app.avaliacao-fisica.nova'
import { Route as AppAvaliacaoFisicaIdRouteImport } from './routes/_app.avaliacao-fisica.$id'
import { Route as AppAlunosIdRouteImport } from './routes/_app.alunos.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksZapiReceiveRouteImport } from './routes/api/public/hooks/zapi-receive'
import { Route as ApiPublicHooksZapiBoasVindasRouteImport } from './routes/api/public/hooks/zapi-boas-vindas'
import { Route as ApiPublicHooksResumoFeedbacksGrupoRouteImport } from './routes/api/public/hooks/resumo-feedbacks-grupo'
import { Route as ApiPublicHooksResumoDiarioRouteImport } from './routes/api/public/hooks/resumo-diario'
import { Route as ApiPublicHooksProcessarJobsFeedbackRouteImport } from './routes/api/public/hooks/processar-jobs-feedback'
import { Route as ApiPublicHooksMotorAutomacoesRouteImport } from './routes/api/public/hooks/motor-automacoes'
import { Route as ApiPublicHooksFeedbackLembretesRouteImport } from './routes/api/public/hooks/feedback-lembretes'
import { Route as ApiPublicHooksDispararJobsRouteImport } from './routes/api/public/hooks/disparar-jobs'
import { Route as ApiPublicHooksCuraEntregasRouteImport } from './routes/api/public/hooks/cura-entregas'
import { Route as ApiPublicHooksBoasVindasRetryRouteImport } from './routes/api/public/hooks/boas-vindas-retry'
import { Route as ApiPublicHooksAlertaRenovacoesRouteImport } from './routes/api/public/hooks/alerta-renovacoes'
import { Route as ApiPublicHooksAgendaCiclosRouteImport } from './routes/api/public/hooks/agenda-ciclos'
import { Route as AppFormsIdRespostasRouteImport } from './routes/_app.forms.$id.respostas'
import { Route as AppAvaliacaoFisicaIdEditarRouteImport } from './routes/_app.avaliacao-fisica.$id.editar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackQuinzenalRoute = FeedbackQuinzenalRouteImport.update({
  id: '/feedback-quinzenal',
  path: '/feedback-quinzenal',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackMensalRoute = FeedbackMensalRouteImport.update({
  id: '/feedback-mensal',
  path: '/feedback-mensal',
  getParentRoute: () => rootRouteImport,
} as any)
const AnamneseRoute = AnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const FormulariosTokenRoute = FormulariosTokenRouteImport.update({
  id: '/formularios/$token',
  path: '/formularios/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoTrocasRoute = AlunoTrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoTrocarSenhaRoute = AlunoTrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoRankingRoute = AlunoRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoPerfilRoute = AlunoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoLoginRoute = AlunoLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoEsqueciSenhaRoute = AlunoEsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoDietaRoute = AlunoDietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoComunidadeRoute = AlunoComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AlunoRoute,
} as any)
const AppVisaoGeralRoute = AppVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbacksRoute = AppFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCaixaSaidaRoute = AppCaixaSaidaRouteImport.update({
  id: '/caixa-saida',
  path: '/caixa-saida',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroIndexRoute = AppFinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppConfiguracoesIndexRoute = AppConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppAvaliacaoFisicaIndexRoute = AppAvaliacaoFisicaIndexRouteImport.update({
  id: '/avaliacao-fisica/',
  path: '/avaliacao-fisica/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlunosIndexRoute = AppAlunosIndexRouteImport.update({
  id: '/alunos/',
  path: '/alunos/',
  getParentRoute: () => AppRoute,
} as any)
const FormulariosIdRespostasRoute = FormulariosIdRespostasRouteImport.update({
  id: '/formularios/$id/respostas',
  path: '/formularios/$id/respostas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFormsIdRoute = AppFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroVendasRoute = AppFinanceiroVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroTransacoesRoute = AppFinanceiroTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroResumoRoute = AppFinanceiroResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroRecebimentosRoute =
  AppFinanceiroRecebimentosRouteImport.update({
    id: '/recebimentos',
    path: '/recebimentos',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroPlanosRoute = AppFinanceiroPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroDespesasRoute = AppFinanceiroDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroContasPagarRoute =
  AppFinanceiroContasPagarRouteImport.update({
    id: '/contas-pagar',
    path: '/contas-pagar',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroClientesRoute = AppFinanceiroClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroCadastrosRoute = AppFinanceiroCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppConfiguracoesUsuariosRoute =
  AppConfiguracoesUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesPermissoesRoute =
  AppConfiguracoesPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesConexoesRoute =
  AppConfiguracoesConexoesRouteImport.update({
    id: '/conexoes',
    path: '/conexoes',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesAutomacoesRoute =
  AppConfiguracoesAutomacoesRouteImport.update({
    id: '/automacoes',
    path: '/automacoes',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppAvaliacaoFisicaNovaRoute = AppAvaliacaoFisicaNovaRouteImport.update({
  id: '/avaliacao-fisica/nova',
  path: '/avaliacao-fisica/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacaoFisicaIdRoute = AppAvaliacaoFisicaIdRouteImport.update({
  id: '/avaliacao-fisica/$id',
  path: '/avaliacao-fisica/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAlunosIdRoute = AppAlunosIdRouteImport.update({
  id: '/alunos/$id',
  path: '/alunos/$id',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksZapiReceiveRoute =
  ApiPublicHooksZapiReceiveRouteImport.update({
    id: '/api/public/hooks/zapi-receive',
    path: '/api/public/hooks/zapi-receive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksZapiBoasVindasRoute =
  ApiPublicHooksZapiBoasVindasRouteImport.update({
    id: '/api/public/hooks/zapi-boas-vindas',
    path: '/api/public/hooks/zapi-boas-vindas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResumoFeedbacksGrupoRoute =
  ApiPublicHooksResumoFeedbacksGrupoRouteImport.update({
    id: '/api/public/hooks/resumo-feedbacks-grupo',
    path: '/api/public/hooks/resumo-feedbacks-grupo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResumoDiarioRoute =
  ApiPublicHooksResumoDiarioRouteImport.update({
    id: '/api/public/hooks/resumo-diario',
    path: '/api/public/hooks/resumo-diario',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessarJobsFeedbackRoute =
  ApiPublicHooksProcessarJobsFeedbackRouteImport.update({
    id: '/api/public/hooks/processar-jobs-feedback',
    path: '/api/public/hooks/processar-jobs-feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMotorAutomacoesRoute =
  ApiPublicHooksMotorAutomacoesRouteImport.update({
    id: '/api/public/hooks/motor-automacoes',
    path: '/api/public/hooks/motor-automacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFeedbackLembretesRoute =
  ApiPublicHooksFeedbackLembretesRouteImport.update({
    id: '/api/public/hooks/feedback-lembretes',
    path: '/api/public/hooks/feedback-lembretes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispararJobsRoute =
  ApiPublicHooksDispararJobsRouteImport.update({
    id: '/api/public/hooks/disparar-jobs',
    path: '/api/public/hooks/disparar-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCuraEntregasRoute =
  ApiPublicHooksCuraEntregasRouteImport.update({
    id: '/api/public/hooks/cura-entregas',
    path: '/api/public/hooks/cura-entregas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBoasVindasRetryRoute =
  ApiPublicHooksBoasVindasRetryRouteImport.update({
    id: '/api/public/hooks/boas-vindas-retry',
    path: '/api/public/hooks/boas-vindas-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAlertaRenovacoesRoute =
  ApiPublicHooksAlertaRenovacoesRouteImport.update({
    id: '/api/public/hooks/alerta-renovacoes',
    path: '/api/public/hooks/alerta-renovacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgendaCiclosRoute =
  ApiPublicHooksAgendaCiclosRouteImport.update({
    id: '/api/public/hooks/agenda-ciclos',
    path: '/api/public/hooks/agenda-ciclos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppFormsIdRespostasRoute = AppFormsIdRespostasRouteImport.update({
  id: '/respostas',
  path: '/respostas',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const AppAvaliacaoFisicaIdEditarRoute =
  AppAvaliacaoFisicaIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AppAvaliacaoFisicaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/anamnese': typeof AnamneseRoute
  '/feedback-mensal': typeof FeedbackMensalRoute
  '/feedback-quinzenal': typeof FeedbackQuinzenalRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/caixa-saida': typeof AppCaixaSaidaRoute
  '/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/feedbacks': typeof AppFeedbacksRoute
  '/financeiro': typeof AppFinanceiroRouteWithChildren
  '/relatorios': typeof AppRelatoriosRoute
  '/visao-geral': typeof AppVisaoGeralRoute
  '/aluno/comunidade': typeof AlunoComunidadeRoute
  '/aluno/dieta': typeof AlunoDietaRoute
  '/aluno/esqueci-senha': typeof AlunoEsqueciSenhaRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/aluno/trocar-senha': typeof AlunoTrocarSenhaRoute
  '/aluno/trocas': typeof AlunoTrocasRoute
  '/f/$slug': typeof FSlugRoute
  '/formularios/$token': typeof FormulariosTokenRoute
  '/aluno/': typeof AlunoIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/alunos/$id': typeof AppAlunosIdRoute
  '/avaliacao-fisica/$id': typeof AppAvaliacaoFisicaIdRouteWithChildren
  '/avaliacao-fisica/nova': typeof AppAvaliacaoFisicaNovaRoute
  '/configuracoes/automacoes': typeof AppConfiguracoesAutomacoesRoute
  '/configuracoes/conexoes': typeof AppConfiguracoesConexoesRoute
  '/configuracoes/permissoes': typeof AppConfiguracoesPermissoesRoute
  '/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
  '/financeiro/cadastros': typeof AppFinanceiroCadastrosRoute
  '/financeiro/clientes': typeof AppFinanceiroClientesRoute
  '/financeiro/contas-pagar': typeof AppFinanceiroContasPagarRoute
  '/financeiro/despesas': typeof AppFinanceiroDespesasRoute
  '/financeiro/planos': typeof AppFinanceiroPlanosRoute
  '/financeiro/recebimentos': typeof AppFinanceiroRecebimentosRoute
  '/financeiro/resumo': typeof AppFinanceiroResumoRoute
  '/financeiro/transacoes': typeof AppFinanceiroTransacoesRoute
  '/financeiro/vendas': typeof AppFinanceiroVendasRoute
  '/forms/$id': typeof AppFormsIdRouteWithChildren
  '/formularios/$id/respostas': typeof FormulariosIdRespostasRoute
  '/alunos/': typeof AppAlunosIndexRoute
  '/avaliacao-fisica/': typeof AppAvaliacaoFisicaIndexRoute
  '/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/financeiro/': typeof AppFinanceiroIndexRoute
  '/forms/': typeof AppFormsIndexRoute
  '/avaliacao-fisica/$id/editar': typeof AppAvaliacaoFisicaIdEditarRoute
  '/forms/$id/respostas': typeof AppFormsIdRespostasRoute
  '/api/public/hooks/agenda-ciclos': typeof ApiPublicHooksAgendaCiclosRoute
  '/api/public/hooks/alerta-renovacoes': typeof ApiPublicHooksAlertaRenovacoesRoute
  '/api/public/hooks/boas-vindas-retry': typeof ApiPublicHooksBoasVindasRetryRoute
  '/api/public/hooks/cura-entregas': typeof ApiPublicHooksCuraEntregasRoute
  '/api/public/hooks/disparar-jobs': typeof ApiPublicHooksDispararJobsRoute
  '/api/public/hooks/feedback-lembretes': typeof ApiPublicHooksFeedbackLembretesRoute
  '/api/public/hooks/motor-automacoes': typeof ApiPublicHooksMotorAutomacoesRoute
  '/api/public/hooks/processar-jobs-feedback': typeof ApiPublicHooksProcessarJobsFeedbackRoute
  '/api/public/hooks/resumo-diario': typeof ApiPublicHooksResumoDiarioRoute
  '/api/public/hooks/resumo-feedbacks-grupo': typeof ApiPublicHooksResumoFeedbacksGrupoRoute
  '/api/public/hooks/zapi-boas-vindas': typeof ApiPublicHooksZapiBoasVindasRoute
  '/api/public/hooks/zapi-receive': typeof ApiPublicHooksZapiReceiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anamnese': typeof AnamneseRoute
  '/feedback-mensal': typeof FeedbackMensalRoute
  '/feedback-quinzenal': typeof FeedbackQuinzenalRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/caixa-saida': typeof AppCaixaSaidaRoute
  '/feedbacks': typeof AppFeedbacksRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/visao-geral': typeof AppVisaoGeralRoute
  '/aluno/comunidade': typeof AlunoComunidadeRoute
  '/aluno/dieta': typeof AlunoDietaRoute
  '/aluno/esqueci-senha': typeof AlunoEsqueciSenhaRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/aluno/trocar-senha': typeof AlunoTrocarSenhaRoute
  '/aluno/trocas': typeof AlunoTrocasRoute
  '/f/$slug': typeof FSlugRoute
  '/formularios/$token': typeof FormulariosTokenRoute
  '/aluno': typeof AlunoIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/alunos/$id': typeof AppAlunosIdRoute
  '/avaliacao-fisica/$id': typeof AppAvaliacaoFisicaIdRouteWithChildren
  '/avaliacao-fisica/nova': typeof AppAvaliacaoFisicaNovaRoute
  '/configuracoes/automacoes': typeof AppConfiguracoesAutomacoesRoute
  '/configuracoes/conexoes': typeof AppConfiguracoesConexoesRoute
  '/configuracoes/permissoes': typeof AppConfiguracoesPermissoesRoute
  '/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
  '/financeiro/cadastros': typeof AppFinanceiroCadastrosRoute
  '/financeiro/clientes': typeof AppFinanceiroClientesRoute
  '/financeiro/contas-pagar': typeof AppFinanceiroContasPagarRoute
  '/financeiro/despesas': typeof AppFinanceiroDespesasRoute
  '/financeiro/planos': typeof AppFinanceiroPlanosRoute
  '/financeiro/recebimentos': typeof AppFinanceiroRecebimentosRoute
  '/financeiro/resumo': typeof AppFinanceiroResumoRoute
  '/financeiro/transacoes': typeof AppFinanceiroTransacoesRoute
  '/financeiro/vendas': typeof AppFinanceiroVendasRoute
  '/forms/$id': typeof AppFormsIdRouteWithChildren
  '/formularios/$id/respostas': typeof FormulariosIdRespostasRoute
  '/alunos': typeof AppAlunosIndexRoute
  '/avaliacao-fisica': typeof AppAvaliacaoFisicaIndexRoute
  '/configuracoes': typeof AppConfiguracoesIndexRoute
  '/financeiro': typeof AppFinanceiroIndexRoute
  '/forms': typeof AppFormsIndexRoute
  '/avaliacao-fisica/$id/editar': typeof AppAvaliacaoFisicaIdEditarRoute
  '/forms/$id/respostas': typeof AppFormsIdRespostasRoute
  '/api/public/hooks/agenda-ciclos': typeof ApiPublicHooksAgendaCiclosRoute
  '/api/public/hooks/alerta-renovacoes': typeof ApiPublicHooksAlertaRenovacoesRoute
  '/api/public/hooks/boas-vindas-retry': typeof ApiPublicHooksBoasVindasRetryRoute
  '/api/public/hooks/cura-entregas': typeof ApiPublicHooksCuraEntregasRoute
  '/api/public/hooks/disparar-jobs': typeof ApiPublicHooksDispararJobsRoute
  '/api/public/hooks/feedback-lembretes': typeof ApiPublicHooksFeedbackLembretesRoute
  '/api/public/hooks/motor-automacoes': typeof ApiPublicHooksMotorAutomacoesRoute
  '/api/public/hooks/processar-jobs-feedback': typeof ApiPublicHooksProcessarJobsFeedbackRoute
  '/api/public/hooks/resumo-diario': typeof ApiPublicHooksResumoDiarioRoute
  '/api/public/hooks/resumo-feedbacks-grupo': typeof ApiPublicHooksResumoFeedbacksGrupoRoute
  '/api/public/hooks/zapi-boas-vindas': typeof ApiPublicHooksZapiBoasVindasRoute
  '/api/public/hooks/zapi-receive': typeof ApiPublicHooksZapiReceiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/anamnese': typeof AnamneseRoute
  '/feedback-mensal': typeof FeedbackMensalRoute
  '/feedback-quinzenal': typeof FeedbackQuinzenalRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/caixa-saida': typeof AppCaixaSaidaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/_app/feedbacks': typeof AppFeedbacksRoute
  '/_app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/visao-geral': typeof AppVisaoGeralRoute
  '/aluno/comunidade': typeof AlunoComunidadeRoute
  '/aluno/dieta': typeof AlunoDietaRoute
  '/aluno/esqueci-senha': typeof AlunoEsqueciSenhaRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/aluno/trocar-senha': typeof AlunoTrocarSenhaRoute
  '/aluno/trocas': typeof AlunoTrocasRoute
  '/f/$slug': typeof FSlugRoute
  '/formularios/$token': typeof FormulariosTokenRoute
  '/aluno/': typeof AlunoIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/alunos/$id': typeof AppAlunosIdRoute
  '/_app/avaliacao-fisica/$id': typeof AppAvaliacaoFisicaIdRouteWithChildren
  '/_app/avaliacao-fisica/nova': typeof AppAvaliacaoFisicaNovaRoute
  '/_app/configuracoes/automacoes': typeof AppConfiguracoesAutomacoesRoute
  '/_app/configuracoes/conexoes': typeof AppConfiguracoesConexoesRoute
  '/_app/configuracoes/permissoes': typeof AppConfiguracoesPermissoesRoute
  '/_app/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
  '/_app/financeiro/cadastros': typeof AppFinanceiroCadastrosRoute
  '/_app/financeiro/clientes': typeof AppFinanceiroClientesRoute
  '/_app/financeiro/contas-pagar': typeof AppFinanceiroContasPagarRoute
  '/_app/financeiro/despesas': typeof AppFinanceiroDespesasRoute
  '/_app/financeiro/planos': typeof AppFinanceiroPlanosRoute
  '/_app/financeiro/recebimentos': typeof AppFinanceiroRecebimentosRoute
  '/_app/financeiro/resumo': typeof AppFinanceiroResumoRoute
  '/_app/financeiro/transacoes': typeof AppFinanceiroTransacoesRoute
  '/_app/financeiro/vendas': typeof AppFinanceiroVendasRoute
  '/_app/forms/$id': typeof AppFormsIdRouteWithChildren
  '/formularios/$id/respostas': typeof FormulariosIdRespostasRoute
  '/_app/alunos/': typeof AppAlunosIndexRoute
  '/_app/avaliacao-fisica/': typeof AppAvaliacaoFisicaIndexRoute
  '/_app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/_app/financeiro/': typeof AppFinanceiroIndexRoute
  '/_app/forms/': typeof AppFormsIndexRoute
  '/_app/avaliacao-fisica/$id/editar': typeof AppAvaliacaoFisicaIdEditarRoute
  '/_app/forms/$id/respostas': typeof AppFormsIdRespostasRoute
  '/api/public/hooks/agenda-ciclos': typeof ApiPublicHooksAgendaCiclosRoute
  '/api/public/hooks/alerta-renovacoes': typeof ApiPublicHooksAlertaRenovacoesRoute
  '/api/public/hooks/boas-vindas-retry': typeof ApiPublicHooksBoasVindasRetryRoute
  '/api/public/hooks/cura-entregas': typeof ApiPublicHooksCuraEntregasRoute
  '/api/public/hooks/disparar-jobs': typeof ApiPublicHooksDispararJobsRoute
  '/api/public/hooks/feedback-lembretes': typeof ApiPublicHooksFeedbackLembretesRoute
  '/api/public/hooks/motor-automacoes': typeof ApiPublicHooksMotorAutomacoesRoute
  '/api/public/hooks/processar-jobs-feedback': typeof ApiPublicHooksProcessarJobsFeedbackRoute
  '/api/public/hooks/resumo-diario': typeof ApiPublicHooksResumoDiarioRoute
  '/api/public/hooks/resumo-feedbacks-grupo': typeof ApiPublicHooksResumoFeedbacksGrupoRoute
  '/api/public/hooks/zapi-boas-vindas': typeof ApiPublicHooksZapiBoasVindasRoute
  '/api/public/hooks/zapi-receive': typeof ApiPublicHooksZapiReceiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/anamnese'
    | '/feedback-mensal'
    | '/feedback-quinzenal'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/caixa-saida'
    | '/configuracoes'
    | '/feedbacks'
    | '/financeiro'
    | '/relatorios'
    | '/visao-geral'
    | '/aluno/comunidade'
    | '/aluno/dieta'
    | '/aluno/esqueci-senha'
    | '/aluno/login'
    | '/aluno/perfil'
    | '/aluno/ranking'
    | '/aluno/trocar-senha'
    | '/aluno/trocas'
    | '/f/$slug'
    | '/formularios/$token'
    | '/aluno/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/alunos/$id'
    | '/avaliacao-fisica/$id'
    | '/avaliacao-fisica/nova'
    | '/configuracoes/automacoes'
    | '/configuracoes/conexoes'
    | '/configuracoes/permissoes'
    | '/configuracoes/usuarios'
    | '/financeiro/cadastros'
    | '/financeiro/clientes'
    | '/financeiro/contas-pagar'
    | '/financeiro/despesas'
    | '/financeiro/planos'
    | '/financeiro/recebimentos'
    | '/financeiro/resumo'
    | '/financeiro/transacoes'
    | '/financeiro/vendas'
    | '/forms/$id'
    | '/formularios/$id/respostas'
    | '/alunos/'
    | '/avaliacao-fisica/'
    | '/configuracoes/'
    | '/financeiro/'
    | '/forms/'
    | '/avaliacao-fisica/$id/editar'
    | '/forms/$id/respostas'
    | '/api/public/hooks/agenda-ciclos'
    | '/api/public/hooks/alerta-renovacoes'
    | '/api/public/hooks/boas-vindas-retry'
    | '/api/public/hooks/cura-entregas'
    | '/api/public/hooks/disparar-jobs'
    | '/api/public/hooks/feedback-lembretes'
    | '/api/public/hooks/motor-automacoes'
    | '/api/public/hooks/processar-jobs-feedback'
    | '/api/public/hooks/resumo-diario'
    | '/api/public/hooks/resumo-feedbacks-grupo'
    | '/api/public/hooks/zapi-boas-vindas'
    | '/api/public/hooks/zapi-receive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anamnese'
    | '/feedback-mensal'
    | '/feedback-quinzenal'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/caixa-saida'
    | '/feedbacks'
    | '/relatorios'
    | '/visao-geral'
    | '/aluno/comunidade'
    | '/aluno/dieta'
    | '/aluno/esqueci-senha'
    | '/aluno/login'
    | '/aluno/perfil'
    | '/aluno/ranking'
    | '/aluno/trocar-senha'
    | '/aluno/trocas'
    | '/f/$slug'
    | '/formularios/$token'
    | '/aluno'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/alunos/$id'
    | '/avaliacao-fisica/$id'
    | '/avaliacao-fisica/nova'
    | '/configuracoes/automacoes'
    | '/configuracoes/conexoes'
    | '/configuracoes/permissoes'
    | '/configuracoes/usuarios'
    | '/financeiro/cadastros'
    | '/financeiro/clientes'
    | '/financeiro/contas-pagar'
    | '/financeiro/despesas'
    | '/financeiro/planos'
    | '/financeiro/recebimentos'
    | '/financeiro/resumo'
    | '/financeiro/transacoes'
    | '/financeiro/vendas'
    | '/forms/$id'
    | '/formularios/$id/respostas'
    | '/alunos'
    | '/avaliacao-fisica'
    | '/configuracoes'
    | '/financeiro'
    | '/forms'
    | '/avaliacao-fisica/$id/editar'
    | '/forms/$id/respostas'
    | '/api/public/hooks/agenda-ciclos'
    | '/api/public/hooks/alerta-renovacoes'
    | '/api/public/hooks/boas-vindas-retry'
    | '/api/public/hooks/cura-entregas'
    | '/api/public/hooks/disparar-jobs'
    | '/api/public/hooks/feedback-lembretes'
    | '/api/public/hooks/motor-automacoes'
    | '/api/public/hooks/processar-jobs-feedback'
    | '/api/public/hooks/resumo-diario'
    | '/api/public/hooks/resumo-feedbacks-grupo'
    | '/api/public/hooks/zapi-boas-vindas'
    | '/api/public/hooks/zapi-receive'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/aluno'
    | '/anamnese'
    | '/feedback-mensal'
    | '/feedback-quinzenal'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/caixa-saida'
    | '/_app/configuracoes'
    | '/_app/feedbacks'
    | '/_app/financeiro'
    | '/_app/relatorios'
    | '/_app/visao-geral'
    | '/aluno/comunidade'
    | '/aluno/dieta'
    | '/aluno/esqueci-senha'
    | '/aluno/login'
    | '/aluno/perfil'
    | '/aluno/ranking'
    | '/aluno/trocar-senha'
    | '/aluno/trocas'
    | '/f/$slug'
    | '/formularios/$token'
    | '/aluno/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/alunos/$id'
    | '/_app/avaliacao-fisica/$id'
    | '/_app/avaliacao-fisica/nova'
    | '/_app/configuracoes/automacoes'
    | '/_app/configuracoes/conexoes'
    | '/_app/configuracoes/permissoes'
    | '/_app/configuracoes/usuarios'
    | '/_app/financeiro/cadastros'
    | '/_app/financeiro/clientes'
    | '/_app/financeiro/contas-pagar'
    | '/_app/financeiro/despesas'
    | '/_app/financeiro/planos'
    | '/_app/financeiro/recebimentos'
    | '/_app/financeiro/resumo'
    | '/_app/financeiro/transacoes'
    | '/_app/financeiro/vendas'
    | '/_app/forms/$id'
    | '/formularios/$id/respostas'
    | '/_app/alunos/'
    | '/_app/avaliacao-fisica/'
    | '/_app/configuracoes/'
    | '/_app/financeiro/'
    | '/_app/forms/'
    | '/_app/avaliacao-fisica/$id/editar'
    | '/_app/forms/$id/respostas'
    | '/api/public/hooks/agenda-ciclos'
    | '/api/public/hooks/alerta-renovacoes'
    | '/api/public/hooks/boas-vindas-retry'
    | '/api/public/hooks/cura-entregas'
    | '/api/public/hooks/disparar-jobs'
    | '/api/public/hooks/feedback-lembretes'
    | '/api/public/hooks/motor-automacoes'
    | '/api/public/hooks/processar-jobs-feedback'
    | '/api/public/hooks/resumo-diario'
    | '/api/public/hooks/resumo-feedbacks-grupo'
    | '/api/public/hooks/zapi-boas-vindas'
    | '/api/public/hooks/zapi-receive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AlunoRoute: typeof AlunoRouteWithChildren
  AnamneseRoute: typeof AnamneseRoute
  FeedbackMensalRoute: typeof FeedbackMensalRoute
  FeedbackQuinzenalRoute: typeof FeedbackQuinzenalRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  FSlugRoute: typeof FSlugRoute
  FormulariosTokenRoute: typeof FormulariosTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  FormulariosIdRespostasRoute: typeof FormulariosIdRespostasRoute
  ApiPublicHooksAgendaCiclosRoute: typeof ApiPublicHooksAgendaCiclosRoute
  ApiPublicHooksAlertaRenovacoesRoute: typeof ApiPublicHooksAlertaRenovacoesRoute
  ApiPublicHooksBoasVindasRetryRoute: typeof ApiPublicHooksBoasVindasRetryRoute
  ApiPublicHooksCuraEntregasRoute: typeof ApiPublicHooksCuraEntregasRoute
  ApiPublicHooksDispararJobsRoute: typeof ApiPublicHooksDispararJobsRoute
  ApiPublicHooksFeedbackLembretesRoute: typeof ApiPublicHooksFeedbackLembretesRoute
  ApiPublicHooksMotorAutomacoesRoute: typeof ApiPublicHooksMotorAutomacoesRoute
  ApiPublicHooksProcessarJobsFeedbackRoute: typeof ApiPublicHooksProcessarJobsFeedbackRoute
  ApiPublicHooksResumoDiarioRoute: typeof ApiPublicHooksResumoDiarioRoute
  ApiPublicHooksResumoFeedbacksGrupoRoute: typeof ApiPublicHooksResumoFeedbacksGrupoRoute
  ApiPublicHooksZapiBoasVindasRoute: typeof ApiPublicHooksZapiBoasVindasRoute
  ApiPublicHooksZapiReceiveRoute: typeof ApiPublicHooksZapiReceiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback-quinzenal': {
      id: '/feedback-quinzenal'
      path: '/feedback-quinzenal'
      fullPath: '/feedback-quinzenal'
      preLoaderRoute: typeof FeedbackQuinzenalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback-mensal': {
      id: '/feedback-mensal'
      path: '/feedback-mensal'
      fullPath: '/feedback-mensal'
      preLoaderRoute: typeof FeedbackMensalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamnese': {
      id: '/anamnese'
      path: '/anamnese'
      fullPath: '/anamnese'
      preLoaderRoute: typeof AnamneseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/formularios/$token': {
      id: '/formularios/$token'
      path: '/formularios/$token'
      fullPath: '/formularios/$token'
      preLoaderRoute: typeof FormulariosTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/trocas': {
      id: '/aluno/trocas'
      path: '/trocas'
      fullPath: '/aluno/trocas'
      preLoaderRoute: typeof AlunoTrocasRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/trocar-senha': {
      id: '/aluno/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/aluno/trocar-senha'
      preLoaderRoute: typeof AlunoTrocarSenhaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/ranking': {
      id: '/aluno/ranking'
      path: '/ranking'
      fullPath: '/aluno/ranking'
      preLoaderRoute: typeof AlunoRankingRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/perfil': {
      id: '/aluno/perfil'
      path: '/perfil'
      fullPath: '/aluno/perfil'
      preLoaderRoute: typeof AlunoPerfilRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/login': {
      id: '/aluno/login'
      path: '/login'
      fullPath: '/aluno/login'
      preLoaderRoute: typeof AlunoLoginRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/esqueci-senha': {
      id: '/aluno/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/aluno/esqueci-senha'
      preLoaderRoute: typeof AlunoEsqueciSenhaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/dieta': {
      id: '/aluno/dieta'
      path: '/dieta'
      fullPath: '/aluno/dieta'
      preLoaderRoute: typeof AlunoDietaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/comunidade': {
      id: '/aluno/comunidade'
      path: '/comunidade'
      fullPath: '/aluno/comunidade'
      preLoaderRoute: typeof AlunoComunidadeRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/_app/visao-geral': {
      id: '/_app/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AppVisaoGeralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedbacks': {
      id: '/_app/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof AppFeedbacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caixa-saida': {
      id: '/_app/caixa-saida'
      path: '/caixa-saida'
      fullPath: '/caixa-saida'
      preLoaderRoute: typeof AppCaixaSaidaRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/forms/': {
      id: '/_app/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/': {
      id: '/_app/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AppFinanceiroIndexRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/configuracoes/': {
      id: '/_app/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AppConfiguracoesIndexRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/_app/avaliacao-fisica/': {
      id: '/_app/avaliacao-fisica/'
      path: '/avaliacao-fisica'
      fullPath: '/avaliacao-fisica/'
      preLoaderRoute: typeof AppAvaliacaoFisicaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alunos/': {
      id: '/_app/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AppAlunosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/formularios/$id/respostas': {
      id: '/formularios/$id/respostas'
      path: '/formularios/$id/respostas'
      fullPath: '/formularios/$id/respostas'
      preLoaderRoute: typeof FormulariosIdRespostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/forms/$id': {
      id: '/_app/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof AppFormsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/vendas': {
      id: '/_app/financeiro/vendas'
      path: '/vendas'
      fullPath: '/financeiro/vendas'
      preLoaderRoute: typeof AppFinanceiroVendasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/transacoes': {
      id: '/_app/financeiro/transacoes'
      path: '/transacoes'
      fullPath: '/financeiro/transacoes'
      preLoaderRoute: typeof AppFinanceiroTransacoesRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/resumo': {
      id: '/_app/financeiro/resumo'
      path: '/resumo'
      fullPath: '/financeiro/resumo'
      preLoaderRoute: typeof AppFinanceiroResumoRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/recebimentos': {
      id: '/_app/financeiro/recebimentos'
      path: '/recebimentos'
      fullPath: '/financeiro/recebimentos'
      preLoaderRoute: typeof AppFinanceiroRecebimentosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/planos': {
      id: '/_app/financeiro/planos'
      path: '/planos'
      fullPath: '/financeiro/planos'
      preLoaderRoute: typeof AppFinanceiroPlanosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/despesas': {
      id: '/_app/financeiro/despesas'
      path: '/despesas'
      fullPath: '/financeiro/despesas'
      preLoaderRoute: typeof AppFinanceiroDespesasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/contas-pagar': {
      id: '/_app/financeiro/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/financeiro/contas-pagar'
      preLoaderRoute: typeof AppFinanceiroContasPagarRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/clientes': {
      id: '/_app/financeiro/clientes'
      path: '/clientes'
      fullPath: '/financeiro/clientes'
      preLoaderRoute: typeof AppFinanceiroClientesRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/cadastros': {
      id: '/_app/financeiro/cadastros'
      path: '/cadastros'
      fullPath: '/financeiro/cadastros'
      preLoaderRoute: typeof AppFinanceiroCadastrosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/configuracoes/usuarios': {
      id: '/_app/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof AppConfiguracoesUsuariosRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/_app/configuracoes/permissoes': {
      id: '/_app/configuracoes/permissoes'
      path: '/permissoes'
      fullPath: '/configuracoes/permissoes'
      preLoaderRoute: typeof AppConfiguracoesPermissoesRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/_app/configuracoes/conexoes': {
      id: '/_app/configuracoes/conexoes'
      path: '/conexoes'
      fullPath: '/configuracoes/conexoes'
      preLoaderRoute: typeof AppConfiguracoesConexoesRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/_app/configuracoes/automacoes': {
      id: '/_app/configuracoes/automacoes'
      path: '/automacoes'
      fullPath: '/configuracoes/automacoes'
      preLoaderRoute: typeof AppConfiguracoesAutomacoesRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/_app/avaliacao-fisica/nova': {
      id: '/_app/avaliacao-fisica/nova'
      path: '/avaliacao-fisica/nova'
      fullPath: '/avaliacao-fisica/nova'
      preLoaderRoute: typeof AppAvaliacaoFisicaNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avaliacao-fisica/$id': {
      id: '/_app/avaliacao-fisica/$id'
      path: '/avaliacao-fisica/$id'
      fullPath: '/avaliacao-fisica/$id'
      preLoaderRoute: typeof AppAvaliacaoFisicaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alunos/$id': {
      id: '/_app/alunos/$id'
      path: '/alunos/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AppAlunosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/zapi-receive': {
      id: '/api/public/hooks/zapi-receive'
      path: '/api/public/hooks/zapi-receive'
      fullPath: '/api/public/hooks/zapi-receive'
      preLoaderRoute: typeof ApiPublicHooksZapiReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/zapi-boas-vindas': {
      id: '/api/public/hooks/zapi-boas-vindas'
      path: '/api/public/hooks/zapi-boas-vindas'
      fullPath: '/api/public/hooks/zapi-boas-vindas'
      preLoaderRoute: typeof ApiPublicHooksZapiBoasVindasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resumo-feedbacks-grupo': {
      id: '/api/public/hooks/resumo-feedbacks-grupo'
      path: '/api/public/hooks/resumo-feedbacks-grupo'
      fullPath: '/api/public/hooks/resumo-feedbacks-grupo'
      preLoaderRoute: typeof ApiPublicHooksResumoFeedbacksGrupoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resumo-diario': {
      id: '/api/public/hooks/resumo-diario'
      path: '/api/public/hooks/resumo-diario'
      fullPath: '/api/public/hooks/resumo-diario'
      preLoaderRoute: typeof ApiPublicHooksResumoDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/processar-jobs-feedback': {
      id: '/api/public/hooks/processar-jobs-feedback'
      path: '/api/public/hooks/processar-jobs-feedback'
      fullPath: '/api/public/hooks/processar-jobs-feedback'
      preLoaderRoute: typeof ApiPublicHooksProcessarJobsFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/motor-automacoes': {
      id: '/api/public/hooks/motor-automacoes'
      path: '/api/public/hooks/motor-automacoes'
      fullPath: '/api/public/hooks/motor-automacoes'
      preLoaderRoute: typeof ApiPublicHooksMotorAutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/feedback-lembretes': {
      id: '/api/public/hooks/feedback-lembretes'
      path: '/api/public/hooks/feedback-lembretes'
      fullPath: '/api/public/hooks/feedback-lembretes'
      preLoaderRoute: typeof ApiPublicHooksFeedbackLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/disparar-jobs': {
      id: '/api/public/hooks/disparar-jobs'
      path: '/api/public/hooks/disparar-jobs'
      fullPath: '/api/public/hooks/disparar-jobs'
      preLoaderRoute: typeof ApiPublicHooksDispararJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cura-entregas': {
      id: '/api/public/hooks/cura-entregas'
      path: '/api/public/hooks/cura-entregas'
      fullPath: '/api/public/hooks/cura-entregas'
      preLoaderRoute: typeof ApiPublicHooksCuraEntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/boas-vindas-retry': {
      id: '/api/public/hooks/boas-vindas-retry'
      path: '/api/public/hooks/boas-vindas-retry'
      fullPath: '/api/public/hooks/boas-vindas-retry'
      preLoaderRoute: typeof ApiPublicHooksBoasVindasRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/alerta-renovacoes': {
      id: '/api/public/hooks/alerta-renovacoes'
      path: '/api/public/hooks/alerta-renovacoes'
      fullPath: '/api/public/hooks/alerta-renovacoes'
      preLoaderRoute: typeof ApiPublicHooksAlertaRenovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agenda-ciclos': {
      id: '/api/public/hooks/agenda-ciclos'
      path: '/api/public/hooks/agenda-ciclos'
      fullPath: '/api/public/hooks/agenda-ciclos'
      preLoaderRoute: typeof ApiPublicHooksAgendaCiclosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/forms/$id/respostas': {
      id: '/_app/forms/$id/respostas'
      path: '/respostas'
      fullPath: '/forms/$id/respostas'
      preLoaderRoute: typeof AppFormsIdRespostasRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/_app/avaliacao-fisica/$id/editar': {
      id: '/_app/avaliacao-fisica/$id/editar'
      path: '/editar'
      fullPath: '/avaliacao-fisica/$id/editar'
      preLoaderRoute: typeof AppAvaliacaoFisicaIdEditarRouteImport
      parentRoute: typeof AppAvaliacaoFisicaIdRoute
    }
  }
}

interface AppConfiguracoesRouteChildren {
  AppConfiguracoesAutomacoesRoute: typeof AppConfiguracoesAutomacoesRoute
  AppConfiguracoesConexoesRoute: typeof AppConfiguracoesConexoesRoute
  AppConfiguracoesPermissoesRoute: typeof AppConfiguracoesPermissoesRoute
  AppConfiguracoesUsuariosRoute: typeof AppConfiguracoesUsuariosRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
}

const AppConfiguracoesRouteChildren: AppConfiguracoesRouteChildren = {
  AppConfiguracoesAutomacoesRoute: AppConfiguracoesAutomacoesRoute,
  AppConfiguracoesConexoesRoute: AppConfiguracoesConexoesRoute,
  AppConfiguracoesPermissoesRoute: AppConfiguracoesPermissoesRoute,
  AppConfiguracoesUsuariosRoute: AppConfiguracoesUsuariosRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
}

const AppConfiguracoesRouteWithChildren =
  AppConfiguracoesRoute._addFileChildren(AppConfiguracoesRouteChildren)

interface AppFinanceiroRouteChildren {
  AppFinanceiroCadastrosRoute: typeof AppFinanceiroCadastrosRoute
  AppFinanceiroClientesRoute: typeof AppFinanceiroClientesRoute
  AppFinanceiroContasPagarRoute: typeof AppFinanceiroContasPagarRoute
  AppFinanceiroDespesasRoute: typeof AppFinanceiroDespesasRoute
  AppFinanceiroPlanosRoute: typeof AppFinanceiroPlanosRoute
  AppFinanceiroRecebimentosRoute: typeof AppFinanceiroRecebimentosRoute
  AppFinanceiroResumoRoute: typeof AppFinanceiroResumoRoute
  AppFinanceiroTransacoesRoute: typeof AppFinanceiroTransacoesRoute
  AppFinanceiroVendasRoute: typeof AppFinanceiroVendasRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
}

const AppFinanceiroRouteChildren: AppFinanceiroRouteChildren = {
  AppFinanceiroCadastrosRoute: AppFinanceiroCadastrosRoute,
  AppFinanceiroClientesRoute: AppFinanceiroClientesRoute,
  AppFinanceiroContasPagarRoute: AppFinanceiroContasPagarRoute,
  AppFinanceiroDespesasRoute: AppFinanceiroDespesasRoute,
  AppFinanceiroPlanosRoute: AppFinanceiroPlanosRoute,
  AppFinanceiroRecebimentosRoute: AppFinanceiroRecebimentosRoute,
  AppFinanceiroResumoRoute: AppFinanceiroResumoRoute,
  AppFinanceiroTransacoesRoute: AppFinanceiroTransacoesRoute,
  AppFinanceiroVendasRoute: AppFinanceiroVendasRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
}

const AppFinanceiroRouteWithChildren = AppFinanceiroRoute._addFileChildren(
  AppFinanceiroRouteChildren,
)

interface AppAvaliacaoFisicaIdRouteChildren {
  AppAvaliacaoFisicaIdEditarRoute: typeof AppAvaliacaoFisicaIdEditarRoute
}

const AppAvaliacaoFisicaIdRouteChildren: AppAvaliacaoFisicaIdRouteChildren = {
  AppAvaliacaoFisicaIdEditarRoute: AppAvaliacaoFisicaIdEditarRoute,
}

const AppAvaliacaoFisicaIdRouteWithChildren =
  AppAvaliacaoFisicaIdRoute._addFileChildren(AppAvaliacaoFisicaIdRouteChildren)

interface AppFormsIdRouteChildren {
  AppFormsIdRespostasRoute: typeof AppFormsIdRespostasRoute
}

const AppFormsIdRouteChildren: AppFormsIdRouteChildren = {
  AppFormsIdRespostasRoute: AppFormsIdRespostasRoute,
}

const AppFormsIdRouteWithChildren = AppFormsIdRoute._addFileChildren(
  AppFormsIdRouteChildren,
)

interface AppRouteChildren {
  AppCaixaSaidaRoute: typeof AppCaixaSaidaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRouteWithChildren
  AppFeedbacksRoute: typeof AppFeedbacksRoute
  AppFinanceiroRoute: typeof AppFinanceiroRouteWithChildren
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppVisaoGeralRoute: typeof AppVisaoGeralRoute
  AppAlunosIdRoute: typeof AppAlunosIdRoute
  AppAvaliacaoFisicaIdRoute: typeof AppAvaliacaoFisicaIdRouteWithChildren
  AppAvaliacaoFisicaNovaRoute: typeof AppAvaliacaoFisicaNovaRoute
  AppFormsIdRoute: typeof AppFormsIdRouteWithChildren
  AppAlunosIndexRoute: typeof AppAlunosIndexRoute
  AppAvaliacaoFisicaIndexRoute: typeof AppAvaliacaoFisicaIndexRoute
  AppFormsIndexRoute: typeof AppFormsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCaixaSaidaRoute: AppCaixaSaidaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRouteWithChildren,
  AppFeedbacksRoute: AppFeedbacksRoute,
  AppFinanceiroRoute: AppFinanceiroRouteWithChildren,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppVisaoGeralRoute: AppVisaoGeralRoute,
  AppAlunosIdRoute: AppAlunosIdRoute,
  AppAvaliacaoFisicaIdRoute: AppAvaliacaoFisicaIdRouteWithChildren,
  AppAvaliacaoFisicaNovaRoute: AppAvaliacaoFisicaNovaRoute,
  AppFormsIdRoute: AppFormsIdRouteWithChildren,
  AppAlunosIndexRoute: AppAlunosIndexRoute,
  AppAvaliacaoFisicaIndexRoute: AppAvaliacaoFisicaIndexRoute,
  AppFormsIndexRoute: AppFormsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AlunoRouteChildren {
  AlunoComunidadeRoute: typeof AlunoComunidadeRoute
  AlunoDietaRoute: typeof AlunoDietaRoute
  AlunoEsqueciSenhaRoute: typeof AlunoEsqueciSenhaRoute
  AlunoLoginRoute: typeof AlunoLoginRoute
  AlunoPerfilRoute: typeof AlunoPerfilRoute
  AlunoRankingRoute: typeof AlunoRankingRoute
  AlunoTrocarSenhaRoute: typeof AlunoTrocarSenhaRoute
  AlunoTrocasRoute: typeof AlunoTrocasRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoComunidadeRoute: AlunoComunidadeRoute,
  AlunoDietaRoute: AlunoDietaRoute,
  AlunoEsqueciSenhaRoute: AlunoEsqueciSenhaRoute,
  AlunoLoginRoute: AlunoLoginRoute,
  AlunoPerfilRoute: AlunoPerfilRoute,
  AlunoRankingRoute: AlunoRankingRoute,
  AlunoTrocarSenhaRoute: AlunoTrocarSenhaRoute,
  AlunoTrocasRoute: AlunoTrocasRoute,
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AlunoRoute: AlunoRouteWithChildren,
  AnamneseRoute: AnamneseRoute,
  FeedbackMensalRoute: FeedbackMensalRoute,
  FeedbackQuinzenalRoute: FeedbackQuinzenalRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  FSlugRoute: FSlugRoute,
  FormulariosTokenRoute: FormulariosTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  FormulariosIdRespostasRoute: FormulariosIdRespostasRoute,
  ApiPublicHooksAgendaCiclosRoute: ApiPublicHooksAgendaCiclosRoute,
  ApiPublicHooksAlertaRenovacoesRoute: ApiPublicHooksAlertaRenovacoesRoute,
  ApiPublicHooksBoasVindasRetryRoute: ApiPublicHooksBoasVindasRetryRoute,
  ApiPublicHooksCuraEntregasRoute: ApiPublicHooksCuraEntregasRoute,
  ApiPublicHooksDispararJobsRoute: ApiPublicHooksDispararJobsRoute,
  ApiPublicHooksFeedbackLembretesRoute: ApiPublicHooksFeedbackLembretesRoute,
  ApiPublicHooksMotorAutomacoesRoute: ApiPublicHooksMotorAutomacoesRoute,
  ApiPublicHooksProcessarJobsFeedbackRoute:
    ApiPublicHooksProcessarJobsFeedbackRoute,
  ApiPublicHooksResumoDiarioRoute: ApiPublicHooksResumoDiarioRoute,
  ApiPublicHooksResumoFeedbacksGrupoRoute:
    ApiPublicHooksResumoFeedbacksGrupoRoute,
  ApiPublicHooksZapiBoasVindasRoute: ApiPublicHooksZapiBoasVindasRoute,
  ApiPublicHooksZapiReceiveRoute: ApiPublicHooksZapiReceiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
