REVOKE EXECUTE ON FUNCTION public.tg_recalc_score_agua() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_recalc_score_checkin() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_conversas_atualizar_estado() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_conversas_estado_auditoria() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_formularios_vincular_por_telefone() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_criar_entrega_dia() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_entrega_completa() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_pos_anamnese() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_pos_resposta_feedback() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_agendar_apos_entrega() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.enfileirar_notificacao_novo_aluno() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.agendar_ciclos_alunos_ativos() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.agendar_jobs_apos_entrega(uuid, timestamptz) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.recalcular_score_dia(uuid, date) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_rodar_cron_job(text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_historico_cron_job(text, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_kpis_cron_jobs() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_listar_cron_jobs() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_aluno_dashboard(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_admin(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_crm_user(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_equipe_or_admin(uuid) FROM anon;